# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YyvWHmjvzVB1RkUSXD_3mGW8OZGhN5O4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt         
import seaborn as sns
import datetime as dt

read_file = pd.read_excel ("weather_dataset_stage1 (1).xls")

read_file.to_csv ("weather_dataset_stage1 (1).csv",index = None, header=True)

df1=pd.read_csv("weather_dataset_stage1 (1).csv", header=28, encoding='latin1')

df1.head()

df1.isnull()

df1.isnull().sum()

df1.shape

df1.Date = pd.to_datetime(df1.Date , errors='coerce')

df1

df1.shape

df1.info()

duplicated_rows_df = df1[df1.duplicated()]

duplicated_rows_df.shape

df1.drop(duplicated_rows_df.index,inplace=True)

df1.shape

df1 = df1.drop('Date1', axis=1)

df1.columns

df1.shape

df1.to_csv('df1.csv', index=False)

cat df1.csv

df1.tail()

df1.info()

df1.dtypes

